### ISSUE TITLE
Reporting speed over serial hard capped at 50hz

### ISSUE THREAD

**Issue by massimodeagro** [getis/Arduino-PS2-Mouse-Handler#2]
I'm using this library to read data from 3 identical mice sensors (PAW3515DB). I have no interest in buttons or z-wheel, just in the x- displacement.

The library works fine and I get to print my readings into the serial monitor, which are then read by other scripts on the computer to operate other stuff.
However, no matter how hard I try, the reporting happens every ~0.02 seconds, never faster.

If i disconnect one of the three mice, the speed goes to ~0.013, with only one mouse I get data every ~0.006 seconds. 

It seems that `PS2MouseHandler::get_data` has a hard timing and is slowing me down since I have to call it separately for every one of the three mice.

Initially, I thought that modifying the sampling rate would alleviate the problem, as 200hz * 3 should give me ~65hz, not 50, but apparently, that is not the case. I also tried putting the mice in STREAM mode, but no luck. I tried forcing the mouse in "no scroll wheel mode" and I gain ~0.01s per mouse, which I guess is the time needed to read the 4th byte. Indeed, 0.017 per reading is ~65hz, which makes me think I reached the expected 200hz for each mouse.

Have I encountered a hardware limitation? or is there an obvious solution or workaround that I am missing? My immediate guess is that what's taking the most time is:
```
write(0xeb); // Send Read Data
read_byte(); // Read Ack Byte
```
Inside the  `PS2MouseHandler::get_data` function, as writing i assume is slower. I assume it should be possible to skip this writing in stream mode?

See below the arduino code:

<details>
  <summary>Click to expand!</summary>
  
```
#include <PS2MouseHandler.h>
#define MOUSE0_DATA 4
#define MOUSE0_CLOCK 5

#define MOUSE1_DATA 2
#define MOUSE1_CLOCK 3

#define MOUSE2_DATA 6
#define MOUSE2_CLOCK 7

PS2MouseHandler mouse0(MOUSE0_CLOCK, MOUSE0_DATA, PS2_MOUSE_STREAM);
PS2MouseHandler mouse1(MOUSE1_CLOCK, MOUSE1_DATA, PS2_MOUSE_STREAM);
PS2MouseHandler mouse2(MOUSE2_CLOCK, MOUSE2_DATA, PS2_MOUSE_STREAM);

/**
 * Setup
 */
void setup()
{
  Serial.begin(38400);
  if(mouse0.initialise() != 0){
    // mouse error
  };

  if(mouse1.initialise() != 0){
    // mouse error
  };


    if(mouse2.initialise() != 0){
    // mouse error
  };

  mouse0.set_resolution(2);
  mouse1.set_resolution(2);
  mouse2.set_resolution(2);
  
  mouse0.set_sample_rate(200, false);
  mouse1.set_sample_rate(200, false);
  mouse2.set_sample_rate(200, false);

}

/**
 * Main program loop
 */

unsigned long last_run = millis();

void loop()
{
    if (millis() - last_run > 1) { //this was here in case i needed to get it slower. for now is taking much more than 1ms
            last_run = millis();
            mouse0.get_data();
            mouse1.get_data();
            mouse2.get_data();

            Serial.print(mouse0.x_movement()); // X Movement Data
            Serial.print(",");
            Serial.print(mouse0.y_movement()); // Y Movement Data
            Serial.print(";");

            Serial.print(mouse1.x_movement()); // X Movement Data
            Serial.print(",");
            Serial.print(mouse1.y_movement()); // Y Movement Data
            Serial.print(";");

            Serial.print(mouse2.x_movement()); // X Movement Data
            Serial.print(",");
            Serial.print(mouse2.y_movement()); // Y Movement Data
            Serial.println();
    }
  if(Serial.available()){
    String command = Serial.readStringUntil('\n');
  
    if(command.equals("identify")){
      Serial.println("Three Mice Sensors");
    }
  }
}

```

</details>

**Comment by getis** [comment]
Hi. The wiki page for the PS2 protocol (https://en.wikipedia.org/wiki/PS/2_port#Communication_protocol) suggests a maximum baud rate of 7-12kbit/s.

0.006s for 1 mouse update / 4 bytes / 8 bits per byte gives 5.3kbit/s

Allowing for a bit of latency in the code this is probably about right.

**Comment by massimodeagro** [comment]
I understand! Thank you for the help!
